export const LOGO = "./icons/logo.png"
export const LOGO_SMALL = "./icons/logo_small.png"
export const ICON_SHIPPING = "./icons/icon_shipping.png"
export const ICON_REFRESH = "./icons/icon_refresh.png"
export const ICON_TEA = "./icons/icon_tea.png"
export const ICON_USER = "./icons/icon_user.png"
export const ICON_BOOKMARK = "./icons/icon_bookmark.png"
export const ICON_CART = "./icons/icon_cart.png"
export const ICON_MENU = "./icons/icon_menu.png"
export const LOGO_WITH_TEXT = "./icons/logo_with_text.png"

export const ICON_BOX = "./icons/icon-box.png"
export const ICON_DAILY = "./icons/icon-daily.png"
export const ICON_LOCK = "./icons/icon-lock.png"
export const ICON_CHECK = "./icons/icon-check.png"
export const ICON_PROTECT = "./icons/icon-protect.png"
